// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBHRvmNyg-rYK_ftb-8P4KLOdeR8jwMbA',
    appId: '1:184402308704:android:6d4ed01f6d9f7582f61d05',
    messagingSenderId: '184402308704',
    projectId: 'parkpilot-fe717',
    storageBucket: 'parkpilot-fe717.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ-VkuxngmYU3l-EewEKm1IjfpMOEYgjE',
    appId: '1:184402308704:web:ee3e2e6a606f8f99f61d05',
    messagingSenderId: '184402308704',
    projectId: 'parkpilot-fe717',
    authDomain: 'parkpilot-fe717.firebaseapp.com',
    storageBucket: 'parkpilot-fe717.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ-VkuxngmYU3l-EewEKm1IjfpMOEYgjE',
    appId: '1:184402308704:web:a3baa61ef6d0a98af61d05',
    messagingSenderId: '184402308704',
    projectId: 'parkpilot-fe717',
    authDomain: 'parkpilot-fe717.firebaseapp.com',
    storageBucket: 'parkpilot-fe717.firebasestorage.app',
  );

}